create table if not exists public.affiliates (
  id bigint generated by default as identity primary key,
  category text not null default '家電',
  title text not null default '',
  summary text not null default '',
  status text not null default 'draft' check (status in ('published', 'draft')),
  published_date date not null default current_date,
  slug text not null default '',
  tags text not null default '',
  image_url text not null default '',
  link_url text not null default '',
  html text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists affiliates_slug_unique
  on public.affiliates (slug)
  where slug <> '';

alter table public.affiliates enable row level security;

grant select on public.affiliates to anon, authenticated;
grant select, insert, update, delete on public.affiliates to service_role;

drop policy if exists "Published affiliates are readable" on public.affiliates;
create policy "Published affiliates are readable"
  on public.affiliates for select
  using (status = 'published');

drop policy if exists "Admins can manage affiliates" on public.affiliates;
create policy "Admins can manage affiliates"
  on public.affiliates for all
  using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');
