create table if not exists public.learning_notes (
  id bigint generated by default as identity primary key,
  category text not null default '未分類',
  title text not null default '未命名文章',
  summary text not null default '',
  status text not null default '草稿' check (status in ('已發布', '草稿')),
  published_date date not null default current_date,
  slug text not null default '',
  tags text not null default '',
  cover_url text not null default '',
  blocks jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists learning_notes_status_date_idx
  on public.learning_notes (status, published_date desc, id desc);

create or replace function public.set_learning_notes_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_learning_notes_updated_at on public.learning_notes;

create trigger set_learning_notes_updated_at
before update on public.learning_notes
for each row
execute function public.set_learning_notes_updated_at();

alter table public.learning_notes enable row level security;

grant select on public.learning_notes to anon;
grant select, insert, update, delete on public.learning_notes to authenticated;
grant all on public.learning_notes to service_role;
grant usage, select on sequence public.learning_notes_id_seq to authenticated;
grant usage, select on sequence public.learning_notes_id_seq to service_role;

drop policy if exists "Published learning notes are readable" on public.learning_notes;
create policy "Published learning notes are readable"
on public.learning_notes
for select
to anon, authenticated
using (status = '已發布');

drop policy if exists "Authenticated users can manage learning notes" on public.learning_notes;
create policy "Authenticated users can manage learning notes"
on public.learning_notes
for all
to authenticated
using (true)
with check (true);
