create table if not exists public.word_cards (
  id bigint generated by default as identity primary key,
  category text not null default 'N5',
  kana text not null default '',
  japanese text not null,
  chinese text not null default '',
  example_japanese text not null default '',
  example_chinese text not null default '',
  audio_url text not null default '',
  front_audio_url text not null default '',
  back_audio_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists word_cards_japanese_unique_idx
  on public.word_cards (japanese);

create index if not exists word_cards_category_id_idx
  on public.word_cards (category, id desc);

create or replace function public.set_word_cards_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_word_cards_updated_at on public.word_cards;

create trigger set_word_cards_updated_at
before update on public.word_cards
for each row
execute function public.set_word_cards_updated_at();

alter table public.word_cards enable row level security;

grant select on public.word_cards to anon;
grant select, insert, update, delete on public.word_cards to authenticated;
grant all on public.word_cards to service_role;
grant usage, select on sequence public.word_cards_id_seq to authenticated;
grant usage, select on sequence public.word_cards_id_seq to service_role;

drop policy if exists "Word cards are publicly readable" on public.word_cards;
create policy "Word cards are publicly readable"
on public.word_cards
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users can manage word cards" on public.word_cards;
create policy "Authenticated users can manage word cards"
on public.word_cards
for all
to authenticated
using (true)
with check (true);

insert into public.word_cards (
  category,
  kana,
  japanese,
  chinese,
  example_japanese,
  example_chinese,
  audio_url,
  front_audio_url,
  back_audio_url
)
values (
  'N5',
  'みず',
  '水',
  '水',
  '水(みず)を飲(の)みます。',
  '我喝水。',
  '',
  '',
  ''
)
on conflict (japanese) do nothing;
