create table if not exists public.site_quotes (
  id bigint generated by default as identity primary key,
  text text not null,
  category text not null default '首頁白版',
  japanese text not null default '',
  kana text not null default '',
  chinese text not null default '',
  front_audio_url text not null default '',
  source text not null default '',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_quotes
  add column if not exists category text not null default '首頁白版',
  add column if not exists japanese text not null default '',
  add column if not exists kana text not null default '',
  add column if not exists chinese text not null default '',
  add column if not exists front_audio_url text not null default '';

create index if not exists site_quotes_enabled_id_idx
  on public.site_quotes (enabled, id);

create or replace function public.set_site_quotes_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_site_quotes_updated_at on public.site_quotes;

create trigger set_site_quotes_updated_at
before update on public.site_quotes
for each row
execute function public.set_site_quotes_updated_at();

alter table public.site_quotes enable row level security;

grant select on public.site_quotes to anon;
grant select, insert, update, delete on public.site_quotes to authenticated;
grant all on public.site_quotes to service_role;
grant usage, select on sequence public.site_quotes_id_seq to authenticated;
grant usage, select on sequence public.site_quotes_id_seq to service_role;

drop policy if exists "Site quotes are publicly readable" on public.site_quotes;
create policy "Site quotes are publicly readable"
on public.site_quotes
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users can manage site quotes" on public.site_quotes;
create policy "Authenticated users can manage site quotes"
on public.site_quotes
for all
to authenticated
using (true)
with check (true);

insert into public.site_quotes (text, category, japanese, kana, chinese, front_audio_url, source, enabled)
values
  ('今日', '首頁白版', '今日', 'きょう', '今天', '', '', true),
  ('一つ', '首頁白版', '一つ', 'ひとつ', '一個', '', '', true),
  ('覚える', '首頁白版', '覚える', 'おぼえる', '記住', '', '', true)
on conflict do nothing;
