create table if not exists public.content_reports (
  id bigint generated by default as identity primary key,
  message text not null,
  page_url text,
  screenshot_path text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.content_reports enable row level security;

create index if not exists content_reports_created_at_idx
on public.content_reports (created_at desc);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'content-report-screenshots',
  'content-report-screenshots',
  false,
  10485760,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
