create table if not exists public.quiz_categories (
  id text primary key,
  level text not null default 'N5',
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quiz_categories_level_check check (level in ('N5', 'N4', 'N3', 'N2', 'N1'))
);

create unique index if not exists quiz_categories_level_name_unique_idx
  on public.quiz_categories (level, name);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  level text not null default 'N5',
  category text not null,
  theme text not null default '',
  prompt text not null,
  note text not null default '',
  answer text not null,
  options jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quiz_questions_level_check check (level in ('N5', 'N4', 'N3', 'N2', 'N1')),
  constraint quiz_questions_options_array_check check (jsonb_typeof(options) = 'array')
);

create index if not exists quiz_questions_level_category_id_idx
  on public.quiz_questions (level, category, id desc);

create or replace function public.set_quiz_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_quiz_categories_updated_at on public.quiz_categories;

create trigger set_quiz_categories_updated_at
before update on public.quiz_categories
for each row
execute function public.set_quiz_updated_at();

drop trigger if exists set_quiz_questions_updated_at on public.quiz_questions;

create trigger set_quiz_questions_updated_at
before update on public.quiz_questions
for each row
execute function public.set_quiz_updated_at();

alter table public.quiz_categories enable row level security;
alter table public.quiz_questions enable row level security;

grant select on public.quiz_categories to anon;
grant select, insert, update, delete on public.quiz_categories to authenticated;
grant all on public.quiz_categories to service_role;

grant select on public.quiz_questions to anon;
grant select, insert, update, delete on public.quiz_questions to authenticated;
grant all on public.quiz_questions to service_role;
grant usage, select on sequence public.quiz_questions_id_seq to authenticated;
grant usage, select on sequence public.quiz_questions_id_seq to service_role;

drop policy if exists "Quiz categories are publicly readable" on public.quiz_categories;
create policy "Quiz categories are publicly readable"
on public.quiz_categories
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users can manage quiz categories" on public.quiz_categories;
create policy "Authenticated users can manage quiz categories"
on public.quiz_categories
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Quiz questions are publicly readable" on public.quiz_questions;
create policy "Quiz questions are publicly readable"
on public.quiz_questions
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users can manage quiz questions" on public.quiz_questions;
create policy "Authenticated users can manage quiz questions"
on public.quiz_questions
for all
to authenticated
using (true)
with check (true);

insert into public.quiz_categories (id, level, name)
values ('n5-vocabulary', 'N5', '文字．語彙')
on conflict (id) do update
set level = excluded.level,
    name = excluded.name;

insert into public.quiz_questions (
  level,
  category,
  theme,
  prompt,
  note,
  answer,
  options
)
select
  'N5',
  '文字．語彙',
  'あしたは雨ですか',
  'あしたは雨ですか',
  'あしたは雨(あめ)ですか
明天下雨嗎',
  'あめ',
  '["ゆき", "はれ", "くもり"]'::jsonb
where not exists (
  select 1
  from public.quiz_questions
  where level = 'N5'
    and category = '文字．語彙'
    and prompt = 'あしたは雨ですか'
    and answer = 'あめ'
);
