create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  artist text not null default '',
  description text not null default '',
  tags text not null default '',
  cover_url text not null default '',
  eyebrow text not null default '同步歌詞',
  status text not null default 'draft' check (status in ('published', 'draft')),
  level text not null default 'N5',
  video_id text not null default '',
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  published_date date not null default current_date,
  lyrics jsonb not null default '[]'::jsonb,
  study_summary text not null default '',
  study_blocks jsonb not null default '[]'::jsonb,
  vocabulary jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists songs_status_date_idx
  on public.songs (status, published_date desc, id desc);

create or replace function public.set_songs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_songs_updated_at on public.songs;
create trigger set_songs_updated_at
before update on public.songs
for each row
execute function public.set_songs_updated_at();

alter table public.songs enable row level security;

grant select on public.songs to anon, authenticated;
grant all on public.songs to service_role;
grant usage, select on sequence public.songs_id_seq to service_role;
revoke insert, update, delete on public.songs from anon, authenticated;
revoke usage on sequence public.songs_id_seq from anon, authenticated;

drop policy if exists "Published songs are readable" on public.songs;
create policy "Published songs are readable"
on public.songs
for select
to anon, authenticated
using (status = 'published');

insert into public.songs (
  title, slug, artist, description, eyebrow, status, level, video_id,
  duration_seconds, published_date, lyrics, study_summary, study_blocks, vocabulary
)
values (
  '小さな夢',
  'chiisana-yume',
  '自學日文筆記・日文留音室',
  '跟著影片逐句閱讀日文歌詞、假名與繁體中文翻譯。',
  '同步歌詞試作',
  'published',
  'N4',
  'PRMMBraH_k4',
  185,
  '2026-08-01',
  $$[
    {"section":"Verse","start":5,"end":14,"japanese":"朝(あさ)の光(ひかり)　窓(まど)を開(あ)けて","translation":"在晨光中，打開窗戶"},
    {"section":"Verse","start":14,"end":23,"japanese":"小(ちい)さな夢(ゆめ)を　胸(むね)に抱(だ)いて","translation":"將小小的夢想抱在心中"},
    {"section":"Verse","start":23,"end":32,"japanese":"今日(きょう)も一歩(いっぽ)　前(まえ)へ進(すす)む","translation":"今天也向前跨出一步"},
    {"section":"Verse","start":32,"end":41,"japanese":"言葉(ことば)の種(たね)　未来(みらい)に咲(さ)く","translation":"言語的種子在未來綻放"},
    {"section":"Chorus","start":41,"end":50,"japanese":"学(まな)ぶ心(こころ)　強(つよ)くなる","translation":"求知的心會變得更加堅強"},
    {"section":"Chorus","start":50,"end":59,"japanese":"空(そら)の青(あお)に　願(ねが)いを乗(の)せ","translation":"把願望寄託在蔚藍天空"},
    {"section":"Chorus","start":59,"end":68,"japanese":"一緒(いっしょ)ならば　道(みち)は見(み)える","translation":"只要在一起，就能看見前路"},
    {"section":"Chorus","start":68,"end":78,"japanese":"希望(きぼう)の歌(うた)　響(ひび)けるよ","translation":"讓希望之歌響起吧"},
    {"section":"Verse 2","start":81,"end":90,"japanese":"昼(ひる)の風(かぜ)に　ページめくれば","translation":"在午後的風中翻開書頁"},
    {"section":"Verse 2","start":90,"end":99,"japanese":"新(あたら)しい音(おと)　心(こころ)を呼(よ)ぶ","translation":"嶄新的聲音呼喚著心靈"},
    {"section":"Verse 2","start":99,"end":108,"japanese":"少(すこ)しずつでも　分(わ)かっていく","translation":"即使一點一點，也會逐漸明白"},
    {"section":"Verse 2","start":108,"end":118,"japanese":"日々(ひび)の努力(どりょく)　光(ひかり)に変(か)わる","translation":"每一天的努力都將化為光芒"},
    {"section":"Prechorus","start":118,"end":127,"japanese":"迷(まよ)う時(とき)も　立(た)ち止(ど)まって","translation":"迷惘的時候，也停下腳步"},
    {"section":"Prechorus","start":127,"end":137,"japanese":"見上(みあ)げる空(そら)に　答(こた)えがある","translation":"仰望的天空中藏著答案"},
    {"section":"Bridge","start":140,"end":149,"japanese":"夜(よる)の静(しず)けさ　夢(ゆめ)を描(えが)き","translation":"在夜晚的寧靜中描繪夢想"},
    {"section":"Bridge","start":149,"end":158,"japanese":"明日(あした)の僕(ぼく)に　笑顔(えがお)をくれる","translation":"為明天的我帶來笑容"},
    {"section":"Bridge","start":158,"end":167,"japanese":"どんな壁(かべ)も　越(こ)えて行(い)ける","translation":"無論什麼高牆都能跨越"},
    {"section":"Bridge","start":167,"end":180,"japanese":"小(ちい)さな勇気(ゆうき)　道(みち)を照(て)らす","translation":"小小的勇氣照亮前路"}
  ]$$::jsonb,
  '整理歌曲中的文法、重要表現、單字與延伸例句。',
  $$[
    {"title":"文法解析：～ならば","japanese":"一緒(いっしょ)ならば　道(みち)は見(み)える","explanation":"～ならば表示假設條件，相當於中文的「如果……的話」。比口語常見的「～なら」稍正式。","translation":"只要在一起，就能看見前路。"},
    {"title":"文法解析：～ていく","japanese":"少(すこ)しずつでも　分(わ)かっていく","explanation":"～ていく可以表示某個動作或變化從現在開始，繼續朝未來發展。","translation":"即使一點一點，也會逐漸明白。"}
  ]$$::jsonb,
  $$[
    {"partOfSpeech":"動詞","japanese":"抱(だ)く","translation":"懷抱、抱持"},
    {"partOfSpeech":"動詞","japanese":"響(ひび)く","translation":"響起、迴盪"},
    {"partOfSpeech":"名詞","japanese":"努力(どりょく)","translation":"努力"},
    {"partOfSpeech":"動詞","japanese":"照(て)らす","translation":"照亮"}
  ]$$::jsonb
)
on conflict (slug) do nothing;
